### GET COUNTRY
GET http://localhost:3001/api/countries

### GET ACTIVITIES
GET http://localhost:3001/api/activities

### GET COUNTRY BY QUERY
GET http://localhost:3001/api/countries?name=pEr

### GET COUNTRY BY ID
GET http://localhost:3001/api/countries/DNK

### POST NEW ACTIVITY

POST http://localhost:3001/api/activities
Content-Type: application/json

# esto es un request body
{
    "name":"Soccer",
    "difficulty": 5,
    "duration": 30,
    "season": "Otoño",
    "idCountry": ["Arg","Per","Dnk"]
}